#!/bin/perl
$regex = "(INT|WIP): .+|((FIX|DEL|FET): #[0-9]{7}(, #[0-9]{7})* - [^#]+)";
open(FH,$ARGV[0]);
my @input = <FH>;
 
if($input[0] =~ m/^(${regex})$/)
{
	exit 0;
}
else
{
	print "Comentario no formato invalido.";
	print "\n${regex}";
	exit 1;
}

